services:
  users-service:             # ✅ nombre del contenedor en minúsculas
    build: ./UsersService    # 🟢 ruta física puede tener mayúsculas
    container_name: users-service
    ports:
      - "8081:8081"

  products-service:
    build: ./ProductsService
    container_name: products-service
    ports:
      - "8082:8082"

  orders-service:
    build: ./OrdersService
    container_name: orders-service
    ports:
      - "8083:8083"
    depends_on:
      - users-service
      - products-service

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - users-service
      - products-service
      - orders-service
